### ISSUE TITLE
Detect when an Input is focused?

### ISSUE THREAD

**Issue by andrelevi** [vuplex/xrit-webview-example#4]
I only want to show my custom keyboard UI when an input is focused, so that it can stay hidden otherwise.

Is there some sort of event I can watch to tell if an input has been focused/unfocused?

Thanks

**Comment by BinaryNate** [comment]
Hi, @andrelevi  👋. Thanks again for using 3D WebView! You can use [IWebView.FocusedInputFieldChanged](https://developer.vuplex.com/webview/IWebView#FocusedInputFieldChanged) for that. Just for future reference—for general support questions, please use [the Vuplex support site](https://support.vuplex.com/contact).
