### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by aman2627** [vuplex/xrit-webview-example#6]
Hi didn't found space to ask query so asking you here, I am targeting oculus quest device and want to use XRIT package also with it. Shall I purchase 3d android webview with gecko engine or normal android webview? Please let me know, thanks in advance

**Comment by BinaryNate** [comment]
Hi, @aman2627 👋. Thank you for your interest! For Oculus Quest, I recommend [3D WebView for Android with Gecko Engine](https://store.vuplex.com/webview/android-gecko/).  [This page](https://support.vuplex.com/articles/android-comparison/) describes the differences between the two Android packages. If you have other questions, please let me know through [the Vuplex contact page](https://support.vuplex.com/contact).
