### ISSUE TITLE
How to disable the soft keyboard of Android system?

### ISSUE THREAD

**Issue by wei-kris** [vuplex/xrit-webview-example#7]
Hello, when I click `<input></input>` in the web page, the Android system will automatically pop up the soft keyboard. How can I disable the soft keyboard of the Android system?

**Comment by binarynate** [comment]
Hi, @wei-kris 👋. Thanks for using 3D WebView, and I'm sorry for the inconvenience! I just pushed a commit to master to resolve this issue:

https://github.com/vuplex/xrit-webview-example/commit/0baf571ce889396099a0180745faba737830072d
